// dddCityMap.js
export const DDD_CITIES = {
  "11": { cidade: "São Paulo", estado: "SP" },
  "12": { cidade: "São José dos Campos", estado: "SP" },
  "13": { cidade: "Santos", estado: "SP" },
  "14": { cidade: "Bauru", estado: "SP" },
  "15": { cidade: "Sorocaba", estado: "SP" },
  "16": { cidade: "Ribeirão Preto", estado: "SP" },
  "17": { cidade: "São José do Rio Preto", estado: "SP" },
  "18": { cidade: "Presidente Prudente", estado: "SP" },
  "19": { cidade: "Campinas", estado: "SP" },
  "21": { cidade: "Rio de Janeiro", estado: "RJ" },
  "22": { cidade: "Campos dos Goytacazes", estado: "RJ" },
  "24": { cidade: "Volta Redonda", estado: "RJ" },
  "27": { cidade: "Vitória", estado: "ES" },
  "28": { cidade: "Cachoeiro de Itapemirim", estado: "ES" },
  "31": { cidade: "Belo Horizonte", estado: "MG" },
  "32": { cidade: "Juiz de Fora", estado: "MG" },
  "33": { cidade: "Governador Valadares", estado: "MG" },
  "34": { cidade: "Uberlândia", estado: "MG" },
  "35": { cidade: "Poços de Caldas", estado: "MG" },
  "37": { cidade: "Divinópolis", estado: "MG" },
  "38": { cidade: "Montes Claros", estado: "MG" },
  "41": { cidade: "Curitiba", estado: "PR" },
  "42": { cidade: "Ponta Grossa", estado: "PR" },
  "43": { cidade: "Londrina", estado: "PR" },
  "44": { cidade: "Maringá", estado: "PR" },
  "45": { cidade: "Foz do Iguaçu", estado: "PR" },
  "46": { cidade: "Francisco Beltrão", estado: "PR" },
  "47": { cidade: "Joinville", estado: "SC" },
  "48": { cidade: "Florianópolis", estado: "SC" },
  "49": { cidade: "Chapecó", estado: "SC" },
  "51": { cidade: "Porto Alegre", estado: "RS" },
  "53": { cidade: "Pelotas", estado: "RS" },
  "54": { cidade: "Caxias do Sul", estado: "RS" },
  "55": { cidade: "Santa Maria", estado: "RS" },
  "61": { cidade: "Brasília", estado: "DF" },
  "62": { cidade: "Goiânia", estado: "GO" },
  "63": { cidade: "Palmas", estado: "TO" },
  "64": { cidade: "Rio Verde", estado: "GO" },
  "65": { cidade: "Cuiabá", estado: "MT" },
  "66": { cidade: "Rondonópolis", estado: "MT" },
  "67": { cidade: "Campo Grande", estado: "MS" },
  "68": { cidade: "Rio Branco", estado: "AC" },
  "69": { cidade: "Porto Velho", estado: "RO" },
  "71": { cidade: "Salvador", estado: "BA" },
  "73": { cidade: "Ilhéus", estado: "BA" },
  "74": { cidade: "Juazeiro", estado: "BA" },
  "75": { cidade: "Feira de Santana", estado: "BA" },
  "77": { cidade: "Barreiras", estado: "BA" },
  "79": { cidade: "Aracaju", estado: "SE" },
  "81": { cidade: "Recife", estado: "PE" },
  "82": { cidade: "Maceió", estado: "AL" },
  "83": { cidade: "João Pessoa", estado: "PB" },
  "84": { cidade: "Natal", estado: "RN" },
  "85": { cidade: "Fortaleza", estado: "CE" },
  "86": { cidade: "Teresina", estado: "PI" },
  "87": { cidade: "Petrolina", estado: "PE" },
  "88": { cidade: "Juazeiro do Norte", estado: "CE" },
  "89": { cidade: "Picos", estado: "PI" },
  "91": { cidade: "Belém", estado: "PA" },
  "92": { cidade: "Manaus", estado: "AM" },
  "93": { cidade: "Santarém", estado: "PA" },
  "94": { cidade: "Marabá", estado: "PA" },
  "95": { cidade: "Boa Vista", estado: "RR" },
  "96": { cidade: "Macapá", estado: "AP" },
  "97": { cidade: "Coari", estado: "AM" },
  "98": { cidade: "São Luís", estado: "MA" },
  "99": { cidade: "Imperatriz", estado: "MA" }
};
